on:
  pull_request:
  push:
    branches:
      - main
      - GUI
      - tests

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install package
        run: python -m pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run -a

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.12]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install package
        run: pip install nox

      - name: Test package
        run: nox -s tests
